import type { Meal } from "./types";

let idCounter = 0;
const uid = () => `food-${++idCounter}`;

export const meals: Meal[] = [
  {
    id: "colazione",
    name: "Colazione",
    icon: "☀️",
    categories: [
      {
        id: "col-latticini",
        name: "Latticini / Bevande",
        icon: "🥛",
        items: [
          { id: uid(), name: "Yogurt greco 2%", baseWeight: 100 },
          { id: uid(), name: "Latte di vacca parz. scremato", baseWeight: 150 },
          { id: uid(), name: "Yogurt da latte bianco", baseWeight: 170 },
          { id: uid(), name: "Yogurt di soia", baseWeight: 125 },
          { id: uid(), name: "Centrifugato o estratto (2 frutti + verdura)", baseWeight: 150 },
          { id: uid(), name: "Bevanda alla avena", baseWeight: 150 },
          { id: uid(), name: "Bevanda alla nocciola", baseWeight: 150 },
          { id: uid(), name: "Bevanda al cocco", baseWeight: 150 },
          { id: uid(), name: "Latte di mandorle", baseWeight: 150 },
          { id: uid(), name: "Latte di soia", baseWeight: 150 },
        ],
      },
      {
        id: "col-cereali",
        name: "Cereali / Pane",
        icon: "🍞",
        items: [
          { id: uid(), name: "Fette biscottate integrali", baseWeight: 60 },
          { id: uid(), name: "Pane di tipo integrale", baseWeight: 100 },
          { id: uid(), name: "Biscotti integrali", baseWeight: 50 },
          { id: uid(), name: "Pane es. Lariano bianco/scuro", baseWeight: 80 },
          { id: uid(), name: "Fette biscottate", baseWeight: 60 },
          { id: uid(), name: "Pane di segale", baseWeight: 100 },
          { id: uid(), name: "Fiocchi di avena", baseWeight: 60 },
          { id: uid(), name: "Fiocchi di orzo", baseWeight: 60 },
          { id: uid(), name: "Muesli", baseWeight: 60 },
          { id: uid(), name: "All-Bran Flakes Kellogg's", baseWeight: 60 },
        ],
      },
      {
        id: "col-condimenti",
        name: "Condimenti",
        icon: "🍯",
        items: [
          { id: uid(), name: "Marmellata", baseWeight: 20 },
        ],
      },
    ],
  },
  {
    id: "spuntino-mattina",
    name: "Spuntino Mattina",
    icon: "🍎",
    categories: [
      {
        id: "sm-frutta",
        name: "Frutta",
        icon: "🍇",
        items: [
          { id: uid(), name: "Pere", baseWeight: 250 },
          { id: uid(), name: "Mele", baseWeight: 150 },
          { id: uid(), name: "Mele annurche", baseWeight: 200 },
          { id: uid(), name: "Ananas (fette)", baseWeight: 200 },
          { id: uid(), name: "Banane", baseWeight: 150 },
          { id: uid(), name: "Prugne", baseWeight: 200 },
          { id: uid(), name: "Fragole", baseWeight: 300 },
          { id: uid(), name: "Castagne fresche", baseWeight: 50 },
          { id: uid(), name: "Arance", baseWeight: 250 },
          { id: uid(), name: "Mirtilli", baseWeight: 300 },
          { id: uid(), name: "Kiwi", baseWeight: 200 },
          { id: uid(), name: "Mandarini", baseWeight: 100 },
          { id: uid(), name: "Melone invernale", baseWeight: 300 },
          { id: uid(), name: "Melagrane", baseWeight: 150 },
          { id: uid(), name: "Papaya", baseWeight: 300 },
          { id: uid(), name: "Clementine", baseWeight: 200 },
          { id: uid(), name: "Uva", baseWeight: 150 },
          { id: uid(), name: "Pompelmo", baseWeight: 300 },
          { id: uid(), name: "Mango", baseWeight: 150 },
        ],
      },
      {
        id: "sm-preparazioni",
        name: "Preparazioni / Alternative",
        icon: "🥤",
        items: [
          { id: uid(), name: "Frutta frullata (smoothie)", baseWeight: 100 },
          { id: uid(), name: "Frullato (latte di mandorla o vaccino)", baseWeight: 100 },
          { id: uid(), name: "Omogeneizzato di frutta", baseWeight: 100 },
          { id: uid(), name: "Estratto (2 verdure, 1 frutto)", baseWeight: 150 },
          { id: uid(), name: "Spremuta di arancia", baseWeight: 150 },
          { id: uid(), name: "Barretta Melinda (solo frutta)", baseWeight: 50 },
          { id: uid(), name: "Centrifuga (2 verdure, 1 frutto)", baseWeight: 150 },
          { id: uid(), name: "Ananas secco", baseWeight: 100 },
        ],
      },
      {
        id: "sm-fruttasecca",
        name: "Frutta Secca",
        icon: "🥜",
        items: [
          { id: uid(), name: "Mandorle dolci secche", baseWeight: 20 },
          { id: uid(), name: "Noci secche", baseWeight: 20 },
          { id: uid(), name: "Pinoli", baseWeight: 20 },
          { id: uid(), name: "Noci pecan", baseWeight: 20 },
          { id: uid(), name: "Nocciole secche", baseWeight: 20 },
          { id: uid(), name: "Pistacchi", baseWeight: 20 },
          { id: uid(), name: "Macadamia", baseWeight: 20 },
          { id: uid(), name: "Anacardi", baseWeight: 20 },
        ],
      },
    ],
  },
  {
    id: "pranzo",
    name: "Pranzo",
    icon: "🍝",
    categories: [
      {
        id: "pr-carbo",
        name: "Carboidrati / Basi",
        icon: "🌾",
        items: [
          { id: uid(), name: "Pane di tipo integrale", baseWeight: 150 },
          { id: uid(), name: "Pasta integrale", baseWeight: 100 },
          { id: uid(), name: "Pasta di semola", baseWeight: 100 },
          { id: uid(), name: "Riso integrale", baseWeight: 100 },
          { id: uid(), name: "Riso (basmati)", baseWeight: 100 },
          { id: uid(), name: "Amaranto", baseWeight: 90 },
          { id: uid(), name: "Avena", baseWeight: 110 },
          { id: uid(), name: "Miglio", baseWeight: 90 },
          { id: uid(), name: "Pane di segale", baseWeight: 150 },
          { id: uid(), name: "Farro", baseWeight: 100 },
          { id: uid(), name: "Mais dolce (in scatola)", baseWeight: 200 },
          { id: uid(), name: "Quinoa", baseWeight: 90 },
          { id: uid(), name: "Orzo", baseWeight: 110 },
          { id: uid(), name: "Grano saraceno", baseWeight: 110 },
          { id: uid(), name: "Gnocchi", baseWeight: 230 },
          { id: uid(), name: "Polenta", baseWeight: 150 },
          { id: uid(), name: "Pane es. Lariano bianco/scuro", baseWeight: 120 },
          { id: uid(), name: "Patate", baseWeight: 300 },
        ],
      },
      {
        id: "pr-proteine",
        name: "Proteine",
        icon: "🥩",
        items: [
          // ── Proteine Animali ──
          { id: uid(), name: "Tonno sott'olio sgocciolato", baseWeight: 60, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Vongola", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Triglia", baseWeight: 80, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Salmone fresco", baseWeight: 80, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Salmone affumicato", baseWeight: 80, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Acciughe o alici fresche", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Sarda", baseWeight: 80, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Sgombro o maccarello fresco", baseWeight: 60, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Calamari freschi", baseWeight: 120, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Polpo", baseWeight: 150, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Seppie", baseWeight: 120, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Merluzzo o nasello / baccalà ammollato", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Spigola", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Orata filetti", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Pollo petto", baseWeight: 90, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Vitello magro", baseWeight: 90, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Maiale magro (lombo)", baseWeight: 80, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Tacchino petto", baseWeight: 80, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Pollo intero senza pelle", baseWeight: 80, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Uovo di gallina intero", baseWeight: 60, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          // ── Proteine Vegetali / Legumi ──
          { id: uid(), name: "Legumi in scatola (media)", baseWeight: 100, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Piselli freschi", baseWeight: 150, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Fave", baseWeight: 200, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Lupini deamarizzati", baseWeight: 80, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Hummus di ceci", baseWeight: 60, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Fagioli borlotti in scatola (scolati)", baseWeight: 100, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Fagioli cannellini in scatola (scolati)", baseWeight: 120, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Lenticchie decorticate", baseWeight: 120, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Piselli in scatola", baseWeight: 150, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Legumi secchi (media)", baseWeight: 40, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          // ── Derivati / Alternative Vegetali ──
          { id: uid(), name: "Feta", baseWeight: 60, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Mozzarella di vacca", baseWeight: 60, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Fiocchi di formaggio magro", baseWeight: 80, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Caciottina fresca", baseWeight: 50, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Stracchino", baseWeight: 50, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Ricotta di vacca", baseWeight: 60, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Formaggio di soia (tofu)", baseWeight: 100, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Bistecca di soia", baseWeight: 80, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Tempeh", baseWeight: 60, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          // ── Salumi (indicati 1/7) ──
          { id: uid(), name: "Prosciutto crudo San Daniele magro", baseWeight: 60, note: "1/7", subGroup: "Salumi (indicati 1/7)", subGroupIcon: "🥓" },
          { id: uid(), name: "Prosciutto crudo di Parma magro", baseWeight: 60, note: "1/7", subGroup: "Salumi (indicati 1/7)", subGroupIcon: "🥓" },
          { id: uid(), name: "Bresaola", baseWeight: 60, note: "1/7", subGroup: "Salumi (indicati 1/7)", subGroupIcon: "🥓" },
        ],
      },
      {
        id: "pr-verdure",
        name: "Verdure",
        icon: "🥬",
        items: [
          { id: uid(), name: "Lattuga", baseWeight: 200 },
          { id: uid(), name: "Alghe Wakame secca", baseWeight: 30 },
          { id: uid(), name: "Carote", baseWeight: 250 },
          { id: uid(), name: "Radicchio rosso", baseWeight: 250 },
          { id: uid(), name: "Pomodori da insalata", baseWeight: 300 },
          { id: uid(), name: "Cetrioli", baseWeight: 300 },
          { id: uid(), name: "Asparagi di serra", baseWeight: 200 },
          { id: uid(), name: "Crescione", baseWeight: 100 },
          { id: uid(), name: "Rucola o rughetta", baseWeight: 150 },
          { id: uid(), name: "Peperoni", baseWeight: 300 },
          { id: uid(), name: "Finocchi", baseWeight: 300 },
          { id: uid(), name: "Funghi prataioli coltivati", baseWeight: 200 },
          { id: uid(), name: "Bieta", baseWeight: 300 },
          { id: uid(), name: "Spinaci", baseWeight: 200 },
          { id: uid(), name: "Scarola", baseWeight: 200 },
          { id: uid(), name: "Melanzane", baseWeight: 300 },
          { id: uid(), name: "Fagiolini", baseWeight: 150 },
          { id: uid(), name: "Cavolfiore", baseWeight: 150 },
          { id: uid(), name: "Cavoli di Bruxelles", baseWeight: 150 },
          { id: uid(), name: "Carciofi", baseWeight: 150 },
          { id: uid(), name: "Zucca gialla", baseWeight: 300 },
          { id: uid(), name: "Zucchine", baseWeight: 300 },
          { id: uid(), name: "Germogli di soia", baseWeight: 100 },
          { id: uid(), name: "Verza", baseWeight: 150 },
          { id: uid(), name: "Verdure surgelate (media)", baseWeight: 150 },
        ],
      },
      {
        id: "pr-condimenti",
        name: "Condimenti",
        icon: "🫒",
        items: [
          { id: uid(), name: "Olio di oliva extravergine", baseWeight: 15 },
        ],
      },
    ],
  },
  {
    id: "merenda",
    name: "Merenda",
    icon: "🍊",
    categories: [
      {
        id: "me-frutta",
        name: "Frutta",
        icon: "🍇",
        items: [
          { id: uid(), name: "Mele", baseWeight: 150 },
          { id: uid(), name: "Pere", baseWeight: 250 },
          { id: uid(), name: "Mele annurche", baseWeight: 200 },
          { id: uid(), name: "Ananas (fette)", baseWeight: 200 },
          { id: uid(), name: "Banane", baseWeight: 150 },
          { id: uid(), name: "Prugne", baseWeight: 200 },
          { id: uid(), name: "Fragole", baseWeight: 300 },
          { id: uid(), name: "Castagne fresche", baseWeight: 50 },
          { id: uid(), name: "Arance", baseWeight: 250 },
          { id: uid(), name: "Mirtilli", baseWeight: 300 },
          { id: uid(), name: "Kiwi", baseWeight: 200 },
          { id: uid(), name: "Mandarini", baseWeight: 100 },
          { id: uid(), name: "Melone invernale", baseWeight: 300 },
          { id: uid(), name: "Melagrane", baseWeight: 150 },
          { id: uid(), name: "Papaya", baseWeight: 300 },
          { id: uid(), name: "Clementine", baseWeight: 200 },
          { id: uid(), name: "Uva", baseWeight: 150 },
          { id: uid(), name: "Pompelmo", baseWeight: 300 },
          { id: uid(), name: "Mango", baseWeight: 150 },
        ],
      },
      {
        id: "me-preparazioni",
        name: "Preparazioni / Alternative",
        icon: "🥤",
        items: [
          { id: uid(), name: "Frutta frullata (smoothie)", baseWeight: 100 },
          { id: uid(), name: "Frullato (latte di mandorla o vaccino)", baseWeight: 100 },
          { id: uid(), name: "Omogeneizzato di frutta", baseWeight: 100 },
          { id: uid(), name: "Estratto (2 verdure, 1 frutto)", baseWeight: 150 },
          { id: uid(), name: "Spremuta di arancia", baseWeight: 150 },
          { id: uid(), name: "Barretta Melinda (solo frutta)", baseWeight: 50 },
          { id: uid(), name: "Centrifuga (2 verdure, 1 frutto)", baseWeight: 150 },
          { id: uid(), name: "Ananas secco", baseWeight: 100 },
        ],
      },
    ],
  },
  {
    id: "cena",
    name: "Cena",
    icon: "🌙",
    categories: [
      {
        id: "ce-carbo",
        name: "Carboidrati / Basi",
        icon: "🌾",
        items: [
          { id: uid(), name: "Pasta integrale", baseWeight: 120 },
          { id: uid(), name: "Pane di tipo integrale", baseWeight: 150 },
          { id: uid(), name: "Pasta di semola", baseWeight: 110 },
          { id: uid(), name: "Amaranto", baseWeight: 100 },
          { id: uid(), name: "Riso (basmati)", baseWeight: 120 },
          { id: uid(), name: "Riso integrale", baseWeight: 120 },
          { id: uid(), name: "Avena", baseWeight: 130 },
          { id: uid(), name: "Miglio", baseWeight: 110 },
          { id: uid(), name: "Farro", baseWeight: 120 },
          { id: uid(), name: "Mais dolce (in scatola)", baseWeight: 200 },
          { id: uid(), name: "Quinoa", baseWeight: 110 },
          { id: uid(), name: "Orzo", baseWeight: 120 },
          { id: uid(), name: "Grano saraceno", baseWeight: 120 },
          { id: uid(), name: "Gnocchi", baseWeight: 270 },
          { id: uid(), name: "Polenta", baseWeight: 150 },
          { id: uid(), name: "Pane di segale", baseWeight: 150 },
          { id: uid(), name: "Pane es. Lariano bianco/scuro", baseWeight: 140 },
          { id: uid(), name: "Patate", baseWeight: 300 },
        ],
      },
      {
        id: "ce-proteine",
        name: "Proteine",
        icon: "🥩",
        items: [
          // ── Proteine Animali ──
          { id: uid(), name: "Tonno sott'olio sgocciolato", baseWeight: 80, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Vongola", baseWeight: 130, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Triglia", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Salmone fresco", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Salmone affumicato", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Acciughe o alici fresche", baseWeight: 130, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Sarda", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Sgombro o maccarello fresco", baseWeight: 80, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Calamari freschi", baseWeight: 150, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Polpo", baseWeight: 200, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Seppie", baseWeight: 150, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Merluzzo o nasello / baccalà ammollato", baseWeight: 130, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Spigola", baseWeight: 130, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Orata filetti", baseWeight: 130, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Pollo petto", baseWeight: 120, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Vitello magro", baseWeight: 120, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Maiale magro (lombo)", baseWeight: 100, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Tacchino petto", baseWeight: 110, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Pollo intero senza pelle", baseWeight: 110, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          { id: uid(), name: "Uovo di gallina intero", baseWeight: 60, subGroup: "Proteine Animali", subGroupIcon: "🐟" },
          // ── Proteine Vegetali / Legumi ──
          { id: uid(), name: "Piselli freschi", baseWeight: 300, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Fave", baseWeight: 300, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Lupini deamarizzati", baseWeight: 200, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Hummus di ceci", baseWeight: 230, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Fagioli borlotti in scatola (scolati)", baseWeight: 300, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Fagioli cannellini in scatola (scolati)", baseWeight: 300, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Legumi in scatola (media)", baseWeight: 300, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Lenticchie decorticate", baseWeight: 300, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Piselli in scatola", baseWeight: 300, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          { id: uid(), name: "Legumi secchi (media)", baseWeight: 130, subGroup: "Proteine Vegetali / Legumi", subGroupIcon: "🫘" },
          // ── Derivati / Alternative Vegetali ──
          { id: uid(), name: "Feta", baseWeight: 80, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Mozzarella di vacca", baseWeight: 80, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Fiocchi di formaggio magro", baseWeight: 100, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Caciottina fresca", baseWeight: 70, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Stracchino", baseWeight: 70, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Ricotta di vacca", baseWeight: 80, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Formaggio di soia (tofu)", baseWeight: 130, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Bistecca di soia", baseWeight: 100, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          { id: uid(), name: "Tempeh", baseWeight: 80, subGroup: "Derivati / Alternative Vegetali", subGroupIcon: "🧀" },
          // ── Salumi (indicati 1/7) ──
          { id: uid(), name: "Prosciutto crudo San Daniele magro", baseWeight: 60, note: "1/7", subGroup: "Salumi (indicati 1/7)", subGroupIcon: "🥓" },
          { id: uid(), name: "Prosciutto crudo di Parma magro", baseWeight: 60, note: "1/7", subGroup: "Salumi (indicati 1/7)", subGroupIcon: "🥓" },
          { id: uid(), name: "Bresaola", baseWeight: 60, note: "1/7", subGroup: "Salumi (indicati 1/7)", subGroupIcon: "🥓" },
        ],
      },
      {
        id: "ce-verdure",
        name: "Verdure",
        icon: "🥬",
        items: [
          { id: uid(), name: "Finocchi", baseWeight: 300 },
          { id: uid(), name: "Lattuga", baseWeight: 200 },
          { id: uid(), name: "Carote", baseWeight: 250 },
          { id: uid(), name: "Radicchio rosso", baseWeight: 250 },
          { id: uid(), name: "Pomodori da insalata", baseWeight: 300 },
          { id: uid(), name: "Cetrioli", baseWeight: 300 },
          { id: uid(), name: "Asparagi di serra", baseWeight: 200 },
          { id: uid(), name: "Crescione", baseWeight: 100 },
          { id: uid(), name: "Rucola o rughetta", baseWeight: 150 },
          { id: uid(), name: "Peperoni", baseWeight: 300 },
          { id: uid(), name: "Funghi prataioli coltivati", baseWeight: 200 },
          { id: uid(), name: "Bieta", baseWeight: 300 },
          { id: uid(), name: "Spinaci", baseWeight: 200 },
          { id: uid(), name: "Scarola", baseWeight: 200 },
          { id: uid(), name: "Melanzane", baseWeight: 300 },
          { id: uid(), name: "Fagiolini", baseWeight: 150 },
          { id: uid(), name: "Cavolfiore", baseWeight: 150 },
          { id: uid(), name: "Cavoli di Bruxelles", baseWeight: 150 },
          { id: uid(), name: "Carciofi", baseWeight: 150 },
          { id: uid(), name: "Zucca gialla", baseWeight: 300 },
          { id: uid(), name: "Zucchine", baseWeight: 300 },
          { id: uid(), name: "Germogli di soia", baseWeight: 100 },
          { id: uid(), name: "Verza", baseWeight: 150 },
          { id: uid(), name: "Verdure surgelate (media)", baseWeight: 150 },
        ],
      },
      {
        id: "ce-condimenti",
        name: "Condimenti",
        icon: "🫒",
        items: [
          { id: uid(), name: "Olio di oliva extravergine", baseWeight: 10 },
        ],
      },
    ],
  },
];